name: Selective Checkout and Backup
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  selective-checkout-and-backup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository with all files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            # Include all files from folder1 (fwk folder)
            fsl-properties/**
            
            # Include all files from dir (fsl folder)
            fwk-properties/**
          sparse-checkout-cone-mode: false

      - name: file-remove fwk folder
        run: |
          rm -f fwk-properties/db-mstr-cug.properties
          rm -f fwk-properties/db-sec-cug.properties
          rm -f fwk-properties/fwkredis-cug.properties
          rm -f fwk-properties/fwkredis.properties
          
      - name: Create backup directories with current date and incremental count
        run: |
          whoami
          # Set timezone and get current date
          CURRENT_DATE=$(date +'%Y%m%d')
          
          # Find highest existing count for FWK directory and increment
          FWK_MAX_COUNT=0
          for dir in /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/backup_${CURRENT_DATE}_*; do
            if [ -d "$dir" ]; then
              COUNT=$(echo "$dir" | grep -o '[0-9]*$')
              if [[ "$COUNT" =~ ^[0-9]+$ ]] && [ "$COUNT" -gt "$FWK_MAX_COUNT" ]; then
                FWK_MAX_COUNT=$COUNT
              fi
            fi
          done
          FWK_NEW_COUNT=$((FWK_MAX_COUNT + 1))
          
          # Find highest existing count for FSL directory and increment
          FSL_MAX_COUNT=0
          for dir in /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/backup_${CURRENT_DATE}_*; do
            if [ -d "$dir" ]; then
              COUNT=$(echo "$dir" | grep -o '[0-9]*$')
              if [[ "$COUNT" =~ ^[0-9]+$ ]] && [ "$COUNT" -gt "$FSL_MAX_COUNT" ]; then
                FSL_MAX_COUNT=$COUNT
              fi
            fi
          done
          FSL_NEW_COUNT=$((FSL_MAX_COUNT + 1))
          
          # Create backup directories
          FWK_BACKUP_DIR="/iMobile_3.0_imobile_cug/cloud-config/fwk-properties/backup_${CURRENT_DATE}_${FWK_NEW_COUNT}"
          FSL_BACKUP_DIR="/iMobile_3.0_imobile_cug/cloud-config/fsl-properties/backup_${CURRENT_DATE}_${FSL_NEW_COUNT}"
          
          # Create backup directories (ensure they exist)
          mkdir -p "$FWK_BACKUP_DIR"
          chmod -R 755 "$FWK_BACKUP_DIR"
          mkdir -p "$FSL_BACKUP_DIR"
          chmod -R 755 "$FSL_BACKUP_DIR"
          
          # Export backup directories for use in other steps
          echo "FWK_BACKUP_DIR=$FWK_BACKUP_DIR" >> $GITHUB_ENV
          echo "FSL_BACKUP_DIR=$FSL_BACKUP_DIR" >> $GITHUB_ENV

      - name: Backup existing files (excluding specified files)
        run: |
          # Set permission for files in fwk-properties and fsl-properties directories
          # chmod -R 755 /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
          # chmod -R 755 /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
          
          echo "=== Listing files in FWK directory before backup ==="
          ls -la /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
          
          echo "=== Listing files in FSL directory before backup ==="
          ls -la /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
          
          # Move FWK files directly to backup
          for file in /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              # Skip specified files and backup directories
              if [[ "$filename" != "db-mstr-cug.properties" && "$filename" != "db-sec-cug.properties" && "$filename" != "fwkredis-cug.properties" && "$filename" != "fwkredis.properties" && ! "$filename" =~ ^backup_ ]]; then
                echo "Moving FWK file: $filename to backup"
                mv -v "$file" "$FWK_BACKUP_DIR/"
              fi
            fi
          done
          
          # Move FSL files directly to backup
          for file in /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              # Skip specified files and backup directories
              if [[ "$filename" != "abc1.txt" && "$filename" != "abc2.txt" && ! "$filename" =~ ^backup_ ]]; then
                echo "Moving FSL file: $filename to backup"
                mv -v "$file" "$FSL_BACKUP_DIR/"
              fi
            fi
          done
          
          echo "=== Listing backup directories after move ==="
          echo "FWK backup directory contents:"
          ls -la "$FWK_BACKUP_DIR/"
          
          echo "FSL backup directory contents:"
          ls -la "$FSL_BACKUP_DIR/"
      
      - name: List available files in the repository
        run: |
          echo "=== Listing files in folder1 (fwk files) ==="
          ls -la folder1/
          
          echo "=== Listing files in dir (fsl files) ==="
          ls -la dir/
      
      - name: Copy new files to respective directories
        run: |
            echo "=== Copying new files to respective directories ==="
            # Copy all files from folder1 to fwk-properties directory
            cp -rv folder1/* /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
            
            # Copy all files from dir to fsl-properties directory
            cp -rv dir/* /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
            
            # Set appropriate permissions
            # chmod -R 755 /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
            # chmod -R 755 /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
          
      - name: Verify file operations
        run: |
          echo "=== Final verification ==="
          echo "FWK backup directory contents:"
          ls -la "$FWK_BACKUP_DIR/"
          
          echo "FSL backup directory contents:"
          ls -la "$FSL_BACKUP_DIR/"
          
          echo "Current FWK directory contents:"
          ls -la /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
          
          echo "Current FSL directory contents:"
          ls -la /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
