name: Selective Checkout and Backup
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  selective-checkout-and-backup:
    runs-on: imobile-prod
    steps:
      - name: Checkout repository with all files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            # Include all files from folder1 (fwk folder)
            folder1/**
            
            # Include all files from dir (fsl folder)
            dir/**
          sparse-checkout-cone-mode: false
          
      - name: Create backup directories with current date and incremental count
        run: |
          whoami
          # Set timezone and get current date
          CURRENT_DATE=$(date +'%Y%m%d')
          
          # Find highest existing count for FWK directory and increment
          FWK_MAX_COUNT=0
          for dir in /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/backup_${CURRENT_DATE}_*; do
            if [ -d "$dir" ]; then
              COUNT=$(echo "$dir" | grep -o '[0-9]*$')
              if [[ "$COUNT" =~ ^[0-9]+$ ]] && [ "$COUNT" -gt "$FWK_MAX_COUNT" ]; then
                FWK_MAX_COUNT=$COUNT
              fi
            fi
          done
          FWK_NEW_COUNT=$((FWK_MAX_COUNT + 1))
          
          # Find highest existing count for FSL directory and increment
          FSL_MAX_COUNT=0
          for dir in /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/backup_${CURRENT_DATE}_*; do
            if [ -d "$dir" ]; then
              COUNT=$(echo "$dir" | grep -o '[0-9]*$')
              if [[ "$COUNT" =~ ^[0-9]+$ ]] && [ "$COUNT" -gt "$FSL_MAX_COUNT" ]; then
                FSL_MAX_COUNT=$COUNT
              fi
            fi
          done
          FSL_NEW_COUNT=$((FSL_MAX_COUNT + 1))
          
          # Create backup directories
          FWK_BACKUP_DIR="/iMobile_3.0_imobile_cug/cloud-config/fwk-properties/backup_${CURRENT_DATE}_${FWK_NEW_COUNT}"
          FSL_BACKUP_DIR="/iMobile_3.0_imobile_cug/cloud-config/fsl-properties/backup_${CURRENT_DATE}_${FSL_NEW_COUNT}"
          
          # Create backup directories (ensure they exist)
          mkdir -p "$FWK_BACKUP_DIR"
          chmod -R 755 "$FWK_BACKUP_DIR"
          mkdir -p "$FSL_BACKUP_DIR"
          chmod -R 755 "$FSL_BACKUP_DIR"
          
          # Export backup directories for use in other steps
          echo "FWK_BACKUP_DIR=$FWK_BACKUP_DIR" >> $GITHUB_ENV
          echo "FSL_BACKUP_DIR=$FSL_BACKUP_DIR" >> $GITHUB_ENV

      - name: Backup existing files (excluding specified files)
        run: |
          # Set permission for files in fwk-properties and fsl-properties directories
          # chmod -R 755 /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
          # chmod -R 755 /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
          
          # Move files from fwk-properties to backup (except the specified files)
          find /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/ -type f \
            ! -name "abc1.txt" \
            ! -name "abc2.txt" \
            ! -name "abc3.txt" \
            ! -name "abc3.txt" \
            ! -path "*/backup_*/*" \
            -exec mv {} $FWK_BACKUP_DIR/ \;
          
          # Move files from fsl-properties to backup (except the specified files)
          find /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/ -type f \
            ! -name "abc1.txt" \
            ! -name "abc2.txt" \
            ! -name "abc3.txt" \
            ! -name "abc3.txt" \
            ! -path "*/backup_*/*" \
            -exec mv {} $FSL_BACKUP_DIR/ \;
      
      - name: List available files in the repository
        run: |
          echo "=== Listing files in folder1 (fwk files) ==="
          ls -la folder1/
          
          echo "=== Listing files in dir (fsl files) ==="
          ls -la dir/
      
      - name: Copy new files to respective directories
        run: |
            # Copy all files from folder1 to fwk-properties directory
            cp -r folder1/* /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
            
            # Copy all files from dir to fsl-properties directory
            cp -r dir/* /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
            
            # Set appropriate permissions
            chmod -R 755 /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
            chmod -R 755 /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
          
      - name: Verify file operations
        run: |
          echo "=== Listing FWK backup directory ==="
          ls -la $FWK_BACKUP_DIR/
          
          echo "=== Listing FSL backup directory ==="
          ls -la $FSL_BACKUP_DIR/
          
          echo "=== Listing current FWK directory ==="
          ls -la /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
          
          echo "=== Listing current FSL directory ==="
          ls -la /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
