name: Selective Checkout and Backup
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  selective-checkout-and-backup:
    runs-on: self-hosted
    steps:
      - name: Checkout specific files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            # Include files from folder1
            folder1/file1
            folder1/file2
            folder1/file3
            
            # Include files from dir
            dir/text1
            dir/text2
            dir/text3
          sparse-checkout-cone-mode: false
          
      - name: Create backup directories with current date and incremental count
        run: |
          # Set timezone and get current date
          CURRENT_DATE=$(date +'%Y%m%d')
          
          # Find highest existing count for FWK directory and increment
          FWK_MAX_COUNT=0
          for dir in /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/backup_${CURRENT_DATE}_*; do
            if [ -d "$dir" ]; then
              COUNT=$(echo "$dir" | grep -o '[0-9]*$')
              if [[ "$COUNT" =~ ^[0-9]+$ ]] && [ "$COUNT" -gt "$FWK_MAX_COUNT" ]; then
                FWK_MAX_COUNT=$COUNT
              fi
            fi
          done
          FWK_NEW_COUNT=$((FWK_MAX_COUNT + 1))
          
          # Find highest existing count for FSL directory and increment
          FSL_MAX_COUNT=0
          for dir in /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/backup_${CURRENT_DATE}_*; do
            if [ -d "$dir" ]; then
              COUNT=$(echo "$dir" | grep -o '[0-9]*$')
              if [[ "$COUNT" =~ ^[0-9]+$ ]] && [ "$COUNT" -gt "$FSL_MAX_COUNT" ]; then
                FSL_MAX_COUNT=$COUNT
              fi
            fi
          done
          FSL_NEW_COUNT=$((FSL_MAX_COUNT + 1))
          
          # Create backup directories
          FWK_BACKUP_DIR="/iMobile_3.0_imobile_cug/cloud-config/fwk-properties/backup_${CURRENT_DATE}_${FWK_NEW_COUNT}"
          FSL_BACKUP_DIR="/iMobile_3.0_imobile_cug/cloud-config/fsl-properties/backup_${CURRENT_DATE}_${FSL_NEW_COUNT}"
          
          

          mv /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/file1 $FWK_BACKUP_DIR/
          mv /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/file2 $FWK_BACKUP_DIR/
          mv /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/file3 $FWK_BACKUP_DIR/
          
          mv /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/text1 $FSL_BACKUP_DIR/
          mv /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/text2 $FSL_BACKUP_DIR/
          mv /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/text3 $FSL_BACKUP_DIR/

      
      - name: Copy new files to respective directories
        run: |
            cp folder1/file1 /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/

            cp folder1/file2 /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/

            cp folder1/file3 /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/

            cp dir/text1 /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/

            cp dir/text2 /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/

            cp dir/text3 /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/

          
      - name: Verify file operations
        run: |
          echo "=== Listing FWK backup directory ==="
          ls -la /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
          
          echo "=== Listing FSL backup directory ==="
          ls -la /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
          
          echo "=== Listing current FWK directory ==="
          ls -la /iMobile_3.0_imobile_cug/cloud-config/fwk-properties/
          
          echo "=== Listing current FSL directory ==="
          ls -la /iMobile_3.0_imobile_cug/cloud-config/fsl-properties/
